import { Book } from "lucide-react";
import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { Button } from "~/ui/button";

import { api } from "~/utils/api";

import { createChart } from "lightweight-charts";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const hello = api.hello.useQuery({ text: session?.user.name });

  return (
    <>
      <Head>
        <title>$GME Sim</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <nav className="container mx-auto flex flex-wrap items-center justify-between p-4">
          <Link href="/" className="flex items-center">
            <Image
              src="https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f680.svg"
              alt="Rocket logo"
              width={32}
              height={32}
            ></Image>
          </Link>
          <div className="flex items-center space-x-4">
            <p>{hello.data ? hello.data.greeting : "Loading tRPC query..."}</p>
            <AuthShowcase />
            <PortfolioButton />
          </div>
        </nav>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            <span className="text-purple-400">To The Moon!</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-md flex-col gap-4 rounded-xl bg-white/10 p-4 hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-md">Just the basics</div>
            </Link>
            <Link
              className="flex max-w-sm flex-col gap-4 rounded-xl bg-white/10 p-4 hover:bg-white/20"
              href="/posts"
            >
              <h3 className="relative flex items-center gap-2 text-2xl font-bold">
                <Book />
                Posts
                <span className="absolute top-0 right-52 flex h-5 w-5 animate-bounce items-center justify-center">
                  <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-indigo-700 opacity-75" />
                  <span className="relative inline-flex h-3 w-3 rounded-full bg-indigo-500" />
                </span>
              </h3>
              <div className="text-md">
                See what others post and submit your own
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const PortfolioButton: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className={sessionData ? "" : "hidden"}>
      <Link href="/portfolio">
        <Button variant="destructive">Portfolio</Button>
      </Link>
    </div>
  );
};

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <Button
        variant="ghost"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </div>
  );
};
