import { type NextPage } from "next";
import Head from "next/head";
import { Button } from "~/ui/button";
import { useState } from "react";
import { AdvancedRealTimeChart } from "react-ts-tradingview-widgets";
import { NavBar } from "~/components/NavBar";
import { TransactButton } from "~/components/TransactButton";

type IntervalType =
    | "1"
    | "3"
    | "5"
    | "15"
    | "30"
    | "60"
    | "120"
    | "180"
    | "240"
    | "D"
    | "W";

const Home: NextPage = () => {
    const [int, setInt] = useState<IntervalType>("5");
    return (
        <>
            <Head>
                <title>Stonk Sim</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className="flex flex-col items-center justify-center">
                <h1 className="py-12 text-5xl font-extrabold tracking-tight sm:text-[5rem]">
                    <span className="text-purple-400">To The Moon!</span>
                </h1>
                <div className="space-y-1 p-4 text-center">
                    <div className="flex flex-row space-x-4">
                        <Button onClick={(_) => setInt("5")}>5 minutes</Button>
                        <Button onClick={(_) => setInt("30")}>
                            30 minutes
                        </Button>
                        <Button onClick={(_) => setInt("D")}>1 day</Button>
                    </div>
                </div>
                <div className="container h-96">
                    <AdvancedRealTimeChart
                        theme="dark"
                        autosize={true}
                        interval={int}
                        withdateranges={false}
                        symbol="GME"
                        enable_publishing={false}
                        hide_top_toolbar={true}
                        save_image={false}
                        hide_legend={true}
                        hide_side_toolbar={true}
                        details={false}
                    ></AdvancedRealTimeChart>
                </div>
                <div className="center  p-12">
                    <div className="flex max-w-md flex-col">
                        <TransactButton />
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
